config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'skills#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  resources :skills
  resources :interests

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
  validates :heading, :presence => true
  validates :body, :presence => true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :user
  validates :title, :presence => true
  validates :example, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :skills
  has_many :interests

  devise :registerable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, :presence => true
  validates :password, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
      devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :current_password, :email])
  end

end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  before_action :only => [:new, :edit] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def index
    @interests = Interest.all
  end

  def new
    @interest = Interest.new
  end

  def create
    @interest = Interest.new(interest_params)
    @interest.user_id = current_user.id
    if @interest.save
      flash[:notice] = "Interest is now added"
      redirect_to interests_path
    else
      render :new
    end
  end

  def show
    @interest = Interest.find(params[:id])
    render :display
  end

  def edit
   @interest = Interest.find(params[:id])
  end

  def update
    @interest = Interest.find(params[:id])
      if @interest.update(interest_params)
        flash[:notice] = "Interest is updated"
        redirect_to interests_path
      else
        render :edit
      end
  end

  def destroy
    @interest = Interest.find(params[:id])
    @interest.destroy
    flash[:notice] = "Interest and interest's details are removed"
    redirect_to interests_path
  end

private
  def interest_params
    params.require(:interest).permit(:heading, :body, :user_id)
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  before_action :only => [:new, :edit] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def index
    @skills = Skill.all
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    @skill.user_id = current_user.id
    if @skill.save
      flash[:notice] = "Skill is now added"
      redirect_to skills_path
    else
      render :new
    end
  end

  def show
    @skill = Skill.find(params[:id])
    render :display
  end

  def edit
   @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
      if @skill.update(skill_params)
        flash[:notice] = "Skill is now updated"
        redirect_to skills_path
      else
        render :edit
      end
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    flash[:notice] = "Skill and skill's details are removed"
    redirect_to skills_path
  end

private
  def skill_params
    params.require(:skill).permit(:title, :example, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/interests/_form.html.erb
<%= render "layouts/errors", :object => @interest %>

<%= form_for @interest do |f| %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= f.label :heading, "Heading"%>
      <%= f.text_field :heading, size: 35 %>
    </div>
    <div class="col-md-6">
    <%= f.label :body, "Details" %>
    <%= f.text_area :body, size: "40x10"%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.submit "Update or Add Interest" %>
    </div>
  </div>
</div>
<% end %>
<hr>
<div class="container">
  <h4><%= link_to "Return to Personal Interests", interests_path %></h4>

  <h4><%= link_to "Go Home", skills_path %></h4>
</div>

app/views/interests/display.html.erb
<% if current_user && current_user.admin %>
  <div class="container">
    <p>Admin: <%= link_to "Edit Interest", edit_interest_path(@interest) %> | <%= link_to "Delete Interest", interest_path, :data => {
        :confirm => "You sure?", :method => "delete"
      } %></p>
  </div>
<% end %>
<hr>

<div class="container">
  <h2>Interest Details</h2>
</div>
<div class="container">
<h3><%= @interest.heading %></h3>
<br>
<h3 class="details"><%= @interest.body %></h3>
</div>

<div class="container">
  <h4><%= link_to "Return to Personal Interests", interests_path %></h4>

  <h4><%= link_to "Go Home", skills_path %></h4>
</div>

app/views/interests/edit.htlm.erb
<h1>Edit Interest</h1>

<%= render "form" %>

app/views/interests/edit.html.erb
<h1>Edit Interest</h1>

<%= render "form" %>

app/views/interests/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h2>Ron's Personal Interests</h2>
  </div>
</div>

<div class="container">
<% if @interests.any? %>
<div class="row">
  <div class="col-md-12">
  <h3>Here's a list of Ron's interests. Click on the links below to veiw the details...</h3>
  <br>
  </div>
</div>

<% @interests.each do |interest| %>
<div class="row">
  <div class="col-md-12" align="center">
    <div class="thumbnail">
      <div class="caption">
        <h3><%= link_to interest.heading, interest_path(interest) %></h3>
      </div>
    </div>
  </div>
</div>
<% end %>
<% else %>
  <h2>No intriguing interests...yet!</h2>
<% end %>

<% if current_user && current_user.admin %>
<h5>Admin: <%= link_to "Add a New interest", new_interest_path %></h5>
<% end %>
<hr>
</div>

<div class="container">
  <h4><%= link_to "Go Home", skills_path %></h4>
</div>

app/views/interests/new.html.erb
<h3>Add a New Interest</h3>

<%= render "form" %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops, there's an error.  Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand"><%= link_to "Ron Craig's_Portfolio", root_path %></div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
         <li><%= link_to "Sign out", '/users/sign_out', method: 'delete' %></li>
         <li><%=link_to "Hi, #{current_user.email}", '/' %></li>
         <li><%=link_to "Edit user", '/users/edit' %></li>
       <% else %>
         <li><%= link_to "Sign up", '/users/sign_up' %></li>
         <li><%= link_to "Sign in", '/users/sign_in' %></li>
       <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ron Craig's Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <h4><%= flash[:alert] %></h4>
    <h4><%= flash[:notice] %></h4>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/skills/_form.html.erb
<%= render "layouts/errors", :object => @skill %>

<%= form_for @skill do |f| %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= f.label :title, "Title"%>
      <%= f.text_field :title, size: 35 %>
    </div>
    <div class="col-md-6">
    <%= f.label :example, "Example" %>
    <%= f.text_area :example, size: "40x10"%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.submit "Update or Add Skill" %>
    </div>
  </div>
</div>
<% end %>
<hr>

<h4><%= link_to "Go Home", skills_path %></h4>

app/views/skills/display.html.erb
<% if current_user && current_user.admin %>
  <div class="container">
    <p>Admin: <%= link_to "Edit Skill", edit_skill_path(@skill) %> | <%= link_to "Delete Skill", skill_path, :data => {
        :confirm => "You sure?", :method => "delete"
      } %></p>
  </div>
<% end %>

<hr>
<div class="container">
  <h2>Skill Details</h2>
</div>

<div class="container">
<h3><%= @skill.title %></h3>
<br>
<h3 class="details"><%= @skill.example %></h3>
</div>

<hr>
<div class="container">
  <h4><%= link_to "Go Home", skills_path %></h4>
</div>

app/views/skills/edit.html.erb
<h1>Edit Skill</h1>

<%= render "form" %>

app/views/skills/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h2>Welome to Ron Craig's Portfolio</h2>
  </div>
</div>

<div class="container">
<% if @skills.any? %>
<div class="row">
  <div class="col-md-12">
  <h3>Here's a list of Ron's skills. Click on the links below to veiw the examples...</h3>
  <br>
  </div>
</div>

<% @skills.each do |skill| %>
<div class="row">
  <div class="col-md-12" align="center">
    <div class="thumbnail">
      <div class="caption">
        <h3><%= link_to skill.title, skill_path(skill) %></h3>
      </div>
    </div>
  </div>
</div>
<% end %>
<% else %>
  <h2>No skills to pay the bills...yet!</h2>
<% end %>

<% if current_user && current_user.admin %>
  <h5>Admin: <%= link_to "Add a New Skill", new_skill_path %></h5>
<% end %>
  <hr>
</div>

<div class="container">
  <h3>Click below to view Ron's Interests...</h3>
  <h4><%= link_to "Ron's Interests", interests_path %></h4>
</div>

app/views/skills/new.html.erb
<h3>Add a New Skill</h3>

<%= render "form" %>